### ISSUE TITLE
[coupled_traj_planner-3] process has died

### ISSUE THREAD

**Issue by bxc237** [LIJUNCHENG001/multi_robot_traj_planner#1]
Hi,
Thanks for sharing the code. I install Ipopt 3.13 with ASL, HSL, and MUMPS and successfully compiles the code (except changing the header folder from `coin-or` to `coin` in `/usr/local/include/`, otherwise `cppad` would complain about missing some header files). Then I tried all the launch examples but all give me the same error. Could you help me with this issue? Thank you! 
![image](https://user-images.githubusercontent.com/16990429/113144787-3940dd00-9260-11eb-9d1a-a2e52c21fd95.png)

**Comment by LIJUNCHENG001** [comment]
According to my experience, Ipopt is not correctly installed on your Ubuntu system. Please refer to https://github.com/udacity/CarND-MPC-Project/blob/master/install_Ipopt_CppAD.md for Ipopt installation.

**Comment by bxc237** [comment]
Hi @LIJUNCHENG001 , after following the install process in the link and recompile the node, I can successfully run those launch files now. Thank you!
Then, if I want to use your awesome work on multiple robots with ros navigation stack (e.g. move_base with real-time planning capability), where should I start?

**Comment by JACKLiuDay** [comment]
> Hi @LIJUNCHENG001 , after following the install process in the link and recompile the node, I can successfully run those launch files now. Thank you! Then, if I want to use your awesome work on multiple robots with ros navigation stack (e.g. move_base with real-time planning capability), where should I start?

Hi, I am trying to compile the project with ros melodic and I met some errors like you. 
Could you help me with this issue?
![image](https://user-images.githubusercontent.com/30967867/181181771-beb5e1b5-fc94-4609-addb-6a92fcb6820a.png)
