### ISSUE TITLE
[prioritized_traj_planner-3] process has died [pid 30915

### ISSUE THREAD

**Issue by JACKLiuDay** [LIJUNCHENG001/multi_robot_traj_planner#3]
Hi, thank you for your great work. I want to use your project but I met some problem.
I installed Ipopt3.12.7 and other dependencies. But when I run launch file. It had some errors.
![image](https://user-images.githubusercontent.com/30967867/181157619-9ed3bae5-6374-41c1-88c0-464c197886d9.png)

**Comment by JACKLiuDay** [comment]
Hi, dose this project support for ubuntu18.04 and melodic?

**Comment by JACKLiuDay** [comment]
I found the reason. Ipopt not installed successfully. I installed it with instruction. https://coin-or.github.io/Ipopt/INSTALL.html
One thing must be done. 
![image](https://user-images.githubusercontent.com/30967867/181395241-61dd9683-d94c-4935-b49e-850c9285c007.png)
A code in http://hsl.rl.ac.uk/ipopt must be downloaded. And change its name in HSL folder.

**Comment by LIJUNCHENG001** [comment]
This project supports ROS melodic and noetic.

**Comment by JACKLiuDay** [comment]
> This project supports ROS melodic and noetic.

Thank you for your reply. I have a question. Does this project have a limit on the number of robots? I tired with 2 robots. But when I run the project with 4 robots. It shows some errors.

**Comment by LIJUNCHENG001** [comment]
You need to create a new launch file for 2 robots.
