### ISSUE TITLE
Trajectory optimization failed when the number of the robot increases from 32 to 40.

### ISSUE THREAD

**Issue by panzhangchao** [LIJUNCHENG001/multi_robot_traj_planner#4]
Hello,  when the number of the robot increases from 32 to 40, the trajectory optimization run time is very small, and the trajectory is the initial path. The "qn" in the prioritized_traj_optimization.hpp is zero, not 40. So, the "Solve()" function is not be called. Can you help me to solve this problem.  My email is 2690623941@qq.com. Thank you very much.

**Comment by panzhangchao** [comment]
Hello, thank you for your great work! I find that the "qn" in the  prioritized_traj_optimization.hpp is zero, so I modify the qn to mission.qn. Although the Solve() function can be called, there will occur an error.


  Would you help me to solve this problem?

**Comment by panzhangchao** [comment]
![2022-11-30 15-46-38屏幕截图](https://user-images.githubusercontent.com/39859334/204737432-62739b3d-80bd-41c1-9ad5-3f70f25b5c29.png)

**Comment by LIJUNCHENG001** [comment]
The code has been tested for 32 agents. If you try to expand to 40 agents, please check the mission and detailed algorithm.
